### ISSUE TITLE
Обновление зависимостей `hydra-oauth-client` и `kratos-session`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/auth#6]
### С чем связан запрос на фичу?

Обновить версии пакетов в зависимостях

### Расскажите как вы это себе видите

Обновить версии зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by OsirisAnubiz** [comment]
@Nelfimov
Обновил yarn в этом проекте (переместил из [raijin](https://github.com/atls/raijin) `yarn/cli/dist/yarn.cjs` в `.yarn/releases`)

Но когда пишу `git commit`, то не вылезает консольный интерфейс как в `atls/nestjs`. Мне нужно поставить какую-то дополнительную зависимость или это ошибка самого `raijin`?

**Comment by Nelfimov** [comment]
последний пункт выполнен?

https://t.me/c/1057842456/42128/72066

`yarn install` запускал?

**Comment by OsirisAnubiz** [comment]
@Nelfimov 
> yarn install запускал?

Да, выполнил всё по пунктам

**Comment by OsirisAnubiz** [comment]
Прикрепил ветку с обновлённым `yarn`

**Comment by OsirisAnubiz** [comment]
Статус на конец дня:
- `yarn` бандл не работает при комите, как ожидается, ожидаю

Осталось сделать:
- Не начал, как посмотрят в чём дело с бандлом сделаю

**Comment by Nelfimov** [comment]
все работает, проверяй локально

![image](https://github.com/user-attachments/assets/ec17493f-5651-42d0-999e-614cbfc82085)

Внеси изменения в ts файл

**Comment by OsirisAnubiz** [comment]
### Статус на конец дня
- обновил зависимости
- исправил некорректный ингеграционный тест


### Осталось сделать
- Ничего, ожидаю ревью на [PR](https://github.com/atls/auth/pull/9)
